"""
Random orthogonal-matrix generation routines used to sample the singular vectors (U, V) of the
structure-constants matrix Gamma = U @ diag(S) @ V^T, and in particular to control the
*sparsity* of these matrices as a knob affecting the model's Fisher Information Matrix and
effective dimension. Includes plain Haar-random orthogonal sampling/Gram-Schmidt
orthogonalization, as well as block-sparse orthogonal matrices built as a direct sum of smaller
random orthogonal blocks (permuted on both sides) -- used in the sparsity_Vh scaling experiments
to interpolate between a dense random orthogonal V^T (s=1) and a permutation matrix (s=D).
"""

import math
import numpy as np
import scipy
from sklearn.utils import shuffle



###
### Generate uniformly distributed random vector
###
def uniform_random_vector(D):
    """
    Sample a uniformly (Haar) distributed random unit vector in R^D, obtained as the first
    column of a Haar-random D x D orthogonal matrix.

    Parameters
    ----------
    D : int
        Dimension of the ambient space.

    Returns
    -------
    v : ndarray, shape (D,)
    """
    O = scipy.stats.ortho_group.rvs(dim=D, size=1)
    v = O[:, 0]
    return v



###
### Generate a (D x M) matrix whose M columns are mutually orthogonal and
### normalized vectors, that are also orthogonal to the optional set of 
### vectors provided by ortho_vecs.
###
def gram_schmidt_ortho(M, D, ortho_vecs=None):
    """
    Generate a (D x M) matrix with M mutually orthonormal columns in R^D, spanning a random
    M-dimensional subspace, obtained by Gram-Schmidt orthogonalization of Haar-random vectors.
    If 'ortho_vecs' is supplied, the generated columns are additionally forced to be orthogonal
    to all columns of 'ortho_vecs' (used e.g. to build a biased model's V-matrix with a subspace
    reserved for/orthogonal to a target parameter direction).

    Parameters
    ----------
    M : int
        Number of orthonormal columns to generate.
    D : int
        Ambient dimension.
    ortho_vecs : ndarray, shape (D, no_ortho_vecs), optional
        Existing set of vectors that the generated columns must also be orthogonal to.

    Returns
    -------
    V : ndarray, shape (D, M)
    """
    V = np.zeros((D, M))
    if (ortho_vecs is None):
        v = uniform_random_vector(D)
        vh = v / np.sqrt(np.sum(v**2.0))
        V[:, 0] = vh
        for i in range(1, M):
            vi = uniform_random_vector(D)
            vpi = np.zeros(D)
            for j in range(0, i):
                vj = np.squeeze(V[:, j])
                pj_vi = np.sum(vi * vj) * vj
                vpi = vpi + pj_vi
            vi = vi - vpi
            vhi = vi / np.sqrt(np.sum(vi**2.0))
            V[:, i] = vhi
    else:
        no_ortho_vecs = ortho_vecs.shape[1]
        v = uniform_random_vector(D)
        vp = np.zeros(D)
        for j in range(0, no_ortho_vecs):
            uj = np.squeeze(ortho_vecs[:, j])
            uhj = uj / np.sqrt(np.sum(uj**2.0))
            pj_v = np.sum(v * uhj) * uhj
            vp = vp + pj_v
        v = v - vp
        vh = v / np.sqrt(np.sum(v**2.0))
        V[:, 0] = vh
        for i in range(1, M):
            vi = uniform_random_vector(D)
            vpi = np.zeros(D)
            for j in range(0, no_ortho_vecs):
                uj = np.squeeze(ortho_vecs[:, j])
                uhj = uj / np.sqrt(np.sum(uj**2.0))
                pj_vi = np.sum(vi * uhj) * uhj
                vpi = vpi + pj_vi
            for j in range(0, i):
                vj = np.squeeze(V[:, j])
                pj_vi = np.sum(vi * vj) * vj
                vpi = vpi + pj_vi
            vi = vi - vpi
            vhi = vi / np.sqrt(np.sum(vi**2.0))
            V[:, i] = vhi
    return V



###
### Generate a (D x M) matrix whose M columns are mutually orthogonal and
### normalized vectors, generated by orthogonalizing the set of vectors
### provided as 'seed' in W.
###
def seeded_gram_schmidt_ortho(M, D, W):
    """
    Generate a (D x M) matrix with M mutually orthonormal columns in R^D by Gram-Schmidt
    orthogonalizing a given ("seed") set of M vectors W, rather than fresh random vectors.
    Used e.g. to re-orthogonalize a V-matrix after it has been perturbed by Gaussian noise
    (perturb_V_tensors), so that orthogonality is restored while staying close to the seed.

    Parameters
    ----------
    M : int
        Number of orthonormal columns to generate.
    D : int
        Ambient dimension.
    W : ndarray, shape (D, M)
        Seed vectors to be orthogonalized (in order).

    Returns
    -------
    V : ndarray, shape (D, M)
    """
    V = np.zeros((D, M))
    v = W[:, 0]
    vh = v / np.sqrt(np.sum(v**2.0))
    V[:, 0] = vh
    for i in range(1, M):
        vi = W[:, i]
        vpi = np.zeros(D)
        for j in range(0, i):
            vj = np.squeeze(V[:, j])
            pj_vi = np.sum(vi * vj) * vj
            vpi = vpi + pj_vi
        vi = vi - vpi
        vhi = vi / np.sqrt(np.sum(vi**2.0))
        V[:, i] = vhi
    return V




###
### Generate a (D x D) random permutation matrix.
###
def random_permutation_matrix(D):
    """
    Generate a random (D x D) permutation matrix.

    Parameters
    ----------
    D : int
        Matrix dimension.

    Returns
    -------
    P : ndarray, shape (D, D)
    """
    P = np.eye(D)
    inds = np.arange(D)
    inds = shuffle(inds)
    P = P[:, inds]
    return P




###
### Generate a random sparse orthogonal matrix as:
### V = P1 * (direct_sum_(l=1...s) (V_j)) * transpose(P2)
### where P1, P2 are random permutations and
### V_l are randomly sampled in O(D/s).
### s is a sparsity index and shoud exactly divide D.
### s=D: V is a permutation
### s=1: V is full
###
def random_sparse_orthogonal(D, s):
    """
    Generate a random block-sparse (D x D) orthogonal matrix
        V = P1 @ (direct_sum_{l=1..s} V_l) @ P2^T,
    where P1, P2 are random permutation matrices and each V_l is an independent Haar-random
    orthogonal matrix of size D/s. The sparsity index 's' (which must exactly divide D)
    interpolates between a dense random orthogonal matrix (s=1) and a pure permutation matrix
    (s=D); it is the control parameter used in the sparsity_Vh scaling experiments to study how
    sparsifying the correlation-space rotation V (or U) affects the FIM spectrum and effective
    dimension.

    Parameters
    ----------
    D : int
        Matrix dimension.
    s : int
        Sparsity index (number of orthogonal blocks); must divide D exactly.

    Returns
    -------
    V : ndarray, shape (D, D)
    """
    Db = int(D / s)
    if s==1:
        V = scipy.stats.ortho_group.rvs(dim=D, size=1)
    elif Db==1:
        Vo = np.diag(np.ones(D))
        P1 = random_permutation_matrix(D)
        P2 = random_permutation_matrix(D)
        VP2 = np.matmul(Vo, np.transpose(P2))
        V = np.matmul(P1, VP2)
    else:
        Vs = scipy.stats.ortho_group.rvs(dim=Db, size=s)
        Vo = np.zeros((D, D))
        for l in range(s):
            Vo[(l*Db):((l+1)*Db), (l*Db):((l+1)*Db)] = Vs[l, :, :]
        P1 = random_permutation_matrix(D)
        P2 = random_permutation_matrix(D)
        VP2 = np.matmul(Vo, np.transpose(P2))
        V = np.matmul(P1, VP2)
    return V




###
### Generate a random sparse orthogonal matrix as:
### V = P1 * (direct_sum_(l=1...s) (V_j)) * transpose(P2)
### where P1, P2 are random permutations and
### V_l are randomly sampled in O(D/s).
### s is the number of blocks:
###     there will be s-1 blocks of dimension Db1 = int(floor(D/s))
###     and the last block of dimension Db2 = D-(s-1)*Db1
### s=D: V is a permutation
### s=1: V is full
###
def general_random_sparse_orthogonal(D, s):
    """
    Generalization of random_sparse_orthogonal to an arbitrary number of blocks 's' that need
    not divide D exactly: builds s-1 blocks of dimension Db1 = floor(D/s) plus one last block of
    dimension Db2 = D - (s-1)*Db1, each independently Haar-random orthogonal, and conjugates the
    resulting block-diagonal matrix by two random permutations P1, P2. Falls back to
    random_sparse_orthogonal when s exactly divides D. As with random_sparse_orthogonal, 's' is
    the sparsity control parameter (s=1: dense; s=D: permutation) used in the sparsity_Vh scaling
    experiments.

    Parameters
    ----------
    D : int
        Matrix dimension.
    s : int
        Number of orthogonal blocks (sparsity index); need not divide D.

    Returns
    -------
    V : ndarray, shape (D, D)
    """
    if (math.remainder(D, s)<1.0e-10):
        V = random_sparse_orthogonal(D, s)
    else:
        Db1 = int(np.floor(D / s))
        Db2 = D - (s-1) * Db1
        Vs = scipy.stats.ortho_group.rvs(dim=Db1, size=(s-1))
        Vo = np.zeros((D, D))
        for l in range(s-1):
            Vo[(l*Db1):((l+1)*Db1), (l*Db1):((l+1)*Db1)] = Vs[l, :, :]
        Vs = scipy.stats.ortho_group.rvs(dim=Db2, size=1)
        l = s - 1
        Vo[(l*Db1):(l*Db1+Db2), (l*Db1):(l*Db1+Db2)] = Vs
        P1 = random_permutation_matrix(D)
        P2 = random_permutation_matrix(D)
        VP2 = np.matmul(Vo, np.transpose(P2))
        V = np.matmul(P1, VP2)
    return V